import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel; 
import com.fazecast.jSerialComm.SerialPort;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;  

public class rfid extends javax.swing.JFrame {
  Connection con;
    Statement st;
    ResultSet rs;
    int cone=0;
    DefaultTableModel dtm;
    SerialPort[] s=SerialPort.getCommPorts();
    SerialPort arduport;
    /**
     * Creates new form rfid
     */
    public rfid() {
        initComponents();
        dcc.setDate(new Date());
        dtm=( DefaultTableModel)TB1.getModel();
                asbtn.setVisible(false);
                aubtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB1 = new javax.swing.JTable();
        dcc = new com.toedter.calendar.JDateChooser();
        nametxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        asbtn = new javax.swing.JButton();
        aubtn = new javax.swing.JButton();
        addstaff = new javax.swing.JFrame();
        dptcb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rfidtf = new javax.swing.JTextField();
        emptd = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        namtf = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        adduser = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uacb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nuid = new javax.swing.JTextField();
        npwd = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        rfidsett = new javax.swing.JFrame();
        conbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ardupo = new javax.swing.JComboBox<>();
        contf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usertf = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passtf = new javax.swing.JPasswordField();

        main.setMinimumSize(new java.awt.Dimension(800, 800));

        jButton1.setText("View all");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TB1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "TIME", "IN/OUT", "DEPT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TB1);

        jButton2.setText("Filter by name");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        asbtn.setText("Add Staff");
        asbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asbtnActionPerformed(evt);
            }
        });

        aubtn.setText("Add user");
        aubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main.getContentPane());
        main.getContentPane().setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcc, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(nametxt))
                .addGap(10, 10, 10)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(asbtn)
                    .addComponent(aubtn))
                .addGap(11, 11, 11))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(dcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(asbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aubtn)
                .addGap(40, 40, 40))
        );

        addstaff.setMinimumSize(new java.awt.Dimension(400, 350));
        addstaff.setPreferredSize(new java.awt.Dimension(387, 400));

        dptcb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dptcbMouseClicked(evt);
            }
        });
        dptcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dptcbActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Register new staff");

        jButton4.setText("Add user");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setText("EMPNO");

        jLabel9.setText("RFID");

        jLabel10.setText("Department");

        jLabel11.setText("Name");

        jButton5.setText("Get RFID");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addstaffLayout = new javax.swing.GroupLayout(addstaff.getContentPane());
        addstaff.getContentPane().setLayout(addstaffLayout);
        addstaffLayout.setHorizontalGroup(
            addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addstaffLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addstaffLayout.createSequentialGroup()
                        .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addstaffLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton4))
                            .addComponent(jLabel7)
                            .addGroup(addstaffLayout.createSequentialGroup()
                                .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emptd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(rfidtf, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(34, 34, 34)
                                .addComponent(jButton5))))
                    .addGroup(addstaffLayout.createSequentialGroup()
                        .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namtf)
                            .addComponent(dptcb, 0, 88, Short.MAX_VALUE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        addstaffLayout.setVerticalGroup(
            addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addstaffLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addstaffLayout.createSequentialGroup()
                        .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rfidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addGap(58, 58, 58)
                        .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(namtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(dptcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(25, 25, 25))
                    .addGroup(addstaffLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(20, 20, 20)
                        .addGroup(addstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(emptd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        adduser.setMinimumSize(new java.awt.Dimension(400, 300));
        adduser.setPreferredSize(new java.awt.Dimension(399, 300));

        jLabel5.setText("PASSWORD");

        jLabel6.setText("USER ID");

        uacb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("ADD A NEW USER FOR THIS SOFTWARE");

        jButton3.setText("Add user");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adduserLayout = new javax.swing.GroupLayout(adduser.getContentPane());
        adduser.getContentPane().setLayout(adduserLayout);
        adduserLayout.setHorizontalGroup(
            adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(adduserLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adduserLayout.createSequentialGroup()
                        .addGroup(adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uacb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nuid)
                                .addComponent(npwd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(adduserLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        adduserLayout.setVerticalGroup(
            adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(npwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(uacb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        rfidsett.setMinimumSize(new java.awt.Dimension(340, 100));

        conbtn.setText("RFID Connect");
        conbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conbtnActionPerformed(evt);
            }
        });

        jLabel12.setText("RFID Serialport");

        javax.swing.GroupLayout rfidsettLayout = new javax.swing.GroupLayout(rfidsett.getContentPane());
        rfidsett.getContentPane().setLayout(rfidsettLayout);
        rfidsettLayout.setHorizontalGroup(
            rfidsettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rfidsettLayout.createSequentialGroup()
                .addGroup(rfidsettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rfidsettLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ardupo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(conbtn))
                    .addGroup(rfidsettLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(contf, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        rfidsettLayout.setVerticalGroup(
            rfidsettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rfidsettLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rfidsettLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ardupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contf, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(209, 164));

        jLabel1.setText("User ID");

        jLabel2.setText("Password");

        usertf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertfActionPerformed(evt);
            }
        });

        loginbtn.setText("LOGIN");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usertf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passtf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(loginbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
connect(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String txt=(String)nametxt.getText();
//System.out.print(txt);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://172.16.26.15:3306/db1","root","1234567890");
            st = (Statement) con.createStatement();
         //   String str = "insert into tes1 values(6,'NN','world')";
         //  st.executeUpdate(str);
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            String date = sdf.format(dcc.getDate());
           // System.out.println(date);
            ResultSet rs=st.executeQuery("select rfid.rfid,name.name,Substring(date1,11),io,Dept from rfid INNER JOIN name ON rfid.RFID=name.RFID where Date1 like '%"+date+"%' and name like '%"+txt+"%'  ORDER BY Date1 Desc;");
            while(rs.next()){  
                 Object ob1=new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                    dtm.addRow((Object[]) ob1);
                            } 
            } catch (Exception ex) {
            //System.out.println(ex);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void usertfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertfActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
String user=(String)usertf.getText();
String pass=(String)passtf.getText();
int flag=0;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://172.16.26.15:3306/db1","root","1234567890");
            st = (Statement) con.createStatement();
            ResultSet rs=st.executeQuery("SELECT pass,privilage FROM `users` WHERE id like '"+user+"'");
            while(rs.next()){  
                 Object ob1=new Object[]{rs.getString(1),rs.getString(2)};
                 if(pass.equals(rs.getString(1))){
                             main.setLocationRelativeTo(null);

                     main.setVisible(true);
                     
                 if(rs.getString(2).equals("1")){
                 asbtn.setVisible(true);
                 aubtn.setVisible(true);

                 }
                 else{
                  asbtn.setVisible(false);
                  aubtn.setVisible(false);
                 }
                 
            }
            else
                  JOptionPane.showMessageDialog(this,"Wrong account info ");

            }     
        } catch (Exception ex) {
                                        JOptionPane.showMessageDialog(this,"Error");

           // System.out.println(ex);
        }
        //loginbtn.setVisible(false);
        main.setLocationRelativeTo(null);
       // main.setVisible(true);
       // System.out.println(flag);
    }//GEN-LAST:event_loginbtnActionPerformed

    private void asbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asbtnActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://172.16.26.15:3306/db1","root","1234567890");
            st = (Statement) con.createStatement();
            ResultSet rs=st.executeQuery("SELECT DISTINCT Dept Country FROM name;");
            if(dptcb.getItemCount()>0){
            dptcb.removeAllItems();
            }
            while(rs.next()){  

                    dptcb.addItem((String)rs.getString(1));
                            }     
        } catch (Exception ex) {
           // System.out.println(ex);
        }
        addstaff.setLocationRelativeTo(null);
        addstaff.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_asbtnActionPerformed

    private void aubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aubtnActionPerformed
        adduser.setLocationRelativeTo(null);
        adduser.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_aubtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String user=(String)nuid.getText();
String pass=(String)npwd.getText();
int ua=uacb.getSelectedIndex();
int flag=0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://172.16.26.15:3306/db1","root","1234567890");
            st = (Statement) con.createStatement();
            st.execute("INSERT INTO `users`(`id`, `pass`, `privilage`) VALUES ('"+user+"','"+pass+"',"+ua+")");
                            JOptionPane.showMessageDialog(this,"User Added");

     
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Error");
        }
        //loginbtn.setVisible(false);
 //       System.out.println(flag);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String rfid=(String)rfidtf.getText();
String empno=(String)emptd.getText();
String name=(String)namtf.getText();
String dept=(String)dptcb.getItemAt(dptcb.getSelectedIndex());
           // System.out.println(dept);

int ua=uacb.getSelectedIndex();
int flag=0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://172.16.26.15:3306/db1","root","1234567890");
            st = (Statement) con.createStatement();
            st.execute("INSERT INTO `name`(`RFID`, `EMPNO`, `Name`, `Dept`) VALUES ('"+rfid+"','"+empno+"','"+name+"','"+dept+"')");
             JOptionPane.showMessageDialog(this,"Added Staff.");  
     
        } catch (Exception ex) {
            //if(ex.getMessage().subString(0,9));
            String s=ex.getMessage();
            if(s.substring(0, 9).equals("Duplicate"))
                JOptionPane.showMessageDialog(this,"This RFID is already registered");
        }    }//GEN-LAST:event_jButton4ActionPerformed

    private void dptcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dptcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dptcbActionPerformed

    private void dptcbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dptcbMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://172.16.26.15:3306/db1","root","1234567890");
            st = (Statement) con.createStatement();
            ResultSet rs=st.executeQuery("SELECT Dept Country FROM name;");
            while(rs.next()){  

                    dptcb.addItem((String)rs.getString(1));
                            }     
        } catch (Exception ex) {
           // System.out.println(ex);
        }
    }//GEN-LAST:event_dptcbMouseClicked

    private void conbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conbtnActionPerformed
        int i=ardupo.getSelectedIndex();
        arduport=s[i];
        if(arduport.openPort()){
           // System.out.println("Selected port="+arduport.getSystemPortName());

            arduport.setParity(0);
            arduport.setBaudRate(9600);
            arduport.setNumDataBits(8);
            arduport.setNumStopBits(1);
            arduport.setFlowControl(0);
            rfidsett.setVisible(false);
            cone=1;
            jButton5.doClick();
           }
        else{

           JOptionPane.showMessageDialog(this,"couldnt open port");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_conbtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if(cone==0){
        rfidsett.setVisible(true);
        while((ardupo.getItemCount())>0){
        ardupo.removeItemAt(0);}
        SerialPort ss1;
        s=SerialPort.getCommPorts();
        for(SerialPort port:s) {
           // System.out.println(""+port.getSystemPortName());
            ardupo.addItem(""+port.getSystemPortName());}
}
if(cone==1){
arduport.setComPortTimeouts(SerialPort.TIMEOUT_READ_SEMI_BLOCKING, 0, 0); // Make random progress.
PrintWriter outpu = new PrintWriter(arduport.getOutputStream());
outpu.print("A");
outpu.flush();
    try {
        Thread.sleep(1000);
    } catch (InterruptedException ex) {
        Logger.getLogger(rfid.class.getName()).log(Level.SEVERE, null, ex);
    }
    
                    InputStream in = arduport.getInputStream();
    try {
                   char data=' ';
                   String RFID="";
                   int flag=0;
                   while(flag==0){
                   if(in.available()>0){
                         data= (char)in.read();
                         if(data=='*'){
                         flag=1;
                         }else{
                        // System.out.println(data);
                         RFID=RFID+data;}
  

           
        }}
                   rfidtf.setText(RFID);
                  // System.out.println(RFID);
    } catch (IOException ex) {
        Logger.getLogger(rfid.class.getName()).log(Level.SEVERE, null, ex);
    }

}


    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rfid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rfid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rfid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rfid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() {
                
                new rfid().setVisible(true);

            }


            
        });
    }
   public void connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://172.16.26.15:3306/db1","root","1234567890");
            st = (Statement) con.createStatement();
         //  String str = "insert into tes1 values(6,'NN','world')";
         //  st.executeUpdate(str);
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
            String date = sdf.format(dcc.getDate());
            //System.out.println(date);
            ResultSet rs=st.executeQuery("select rfid.rfid,name.name,Substring(date1,11),io,Dept from rfid INNER JOIN name ON rfid.RFID=name.RFID where Date1 like '%"+date+"%' ORDER BY Date1 Desc;");  
            while(rs.next()){  
                 Object ob1=new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                    dtm.addRow((Object[]) ob1);
         } 
        } catch (Exception ex) {
           // System.out.println(ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB1;
    private javax.swing.JFrame addstaff;
    private javax.swing.JFrame adduser;
    private javax.swing.JComboBox<String> ardupo;
    private javax.swing.JButton asbtn;
    private javax.swing.JButton aubtn;
    private javax.swing.JButton conbtn;
    private javax.swing.JLabel contf;
    private com.toedter.calendar.JDateChooser dcc;
    private javax.swing.JComboBox<String> dptcb;
    private javax.swing.JTextField emptd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginbtn;
    private javax.swing.JFrame main;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField namtf;
    private javax.swing.JTextField npwd;
    private javax.swing.JTextField nuid;
    private javax.swing.JPasswordField passtf;
    private javax.swing.JFrame rfidsett;
    private javax.swing.JTextField rfidtf;
    private javax.swing.JComboBox<String> uacb;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables
}
